-- MySQL Script generated by MySQL Workbench
-- Wed Aug 29 10:41:35 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema practica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema practica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `practica` DEFAULT CHARACTER SET utf8 ;
USE `practica` ;

-- -----------------------------------------------------
-- Table `practica`.`users_information`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica`.`users_information` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(125) NULL,
  `last_name` VARCHAR(125) NULL,
  `email` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `practica`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `practica`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NULL,
  `password` VARCHAR(250) NULL,
  `users_information_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_users_information_idx` (`users_information_id` ASC),
  CONSTRAINT `fk_users_users_information`
    FOREIGN KEY (`users_information_id`)
    REFERENCES `practica`.`users_information` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
